# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f75fc0308061e88d2d73354bad4cf4ece4178add556bd9596308a6598c0c9287a79b2c8f503d77c6ba300c3eeca9481012f440281ade1ae0a04684d5703d28

test:
  secret_key_base: 8234fe367b7cc66fd199e08ca857e1a8772ceb2603edfe4b4bde86075e06cfa4b40121104cc721e246cbb8a5262a0a409862c2289aa56d61c6e48a16a51ecce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
